### ISSUE TITLE
Byte Color Tables transformed to GDAL VRT

### ISSUE THREAD

**Issue by roblabs** [kennethmoreland-com/kennethmoreland-com.github.io#1]
I am interested in using Black Body with an 8-bit TIFF file.  You [sold me](https://github.com/kennethmoreland-com/kennethmoreland-com.github.io/blob/master/color-advice/BadColorMaps.pdf) on avoiding rainbow.
* Black Body color map I prefer to use —  http://www.kennethmoreland.com/color-advice/black-body/black-body-table-byte-0256.csv

Are you aware of any tools that convert this CSV format to [VRT](http://www.gdal.org/gdal_vrttut.html) for use with [GDAL](http://gdal.org)?  

If it doesn't exist, I will end up writing one in Python since much of the GDAL tools are Python.

-----

For example, VRT Color Tables look like this with RGBAlpha data.

```
  <VRTRasterBand dataType="Byte" band="1">
    <Metadata />
    <NoDataValue>0</NoDataValue>
    <ColorInterp>Palette</ColorInterp>
    <ColorTable>
      <Entry c1="8" c2="0" c3="88" c4="255" />
      <Entry c1="9" c2="0" c3="90" c4="255" />
      <Entry c1="10" c2="0" c3="92" c4="255" />
:
# a total of 256 entries are required for the Palette; snipped the middle 250
:
      <Entry c1="254" c2="0" c3="215" c4="255" />
      <Entry c1="254" c2="0" c3="216" c4="255" />
      <Entry c1="0" c2="0" c3="0" c4="255" />
    </ColorTable>
```

**Comment by kmorel** [comment]
I don't know of any tools that specifically do this, but then I've never used VRT color tables. It seems like a pretty simple conversion. The `awk` tool is probably the one most suited for the conversion. Here is a quick `awk` script I drafted up that will probably do the job (or get pretty close).

```awk
BEGIN { FS = "," }
BEGIN { print "<VRTRasterBand dataType=\"Byte\" band=\"1\">" }
BEGIN { print "  <Metadata />" }
BEGIN { print "  <ColorInterp>Palette</ColorInterp>" }
BEGIN { print "  <ColorTable>" }
NR > 1 { print "    <Entry c1=\"" $2 "\" c2=\"" $3 "\" c3=\"" $4 "\" c4=\"255\" />" }
END { print "  </ColorTable>" }
END { print "</VRTRasterBand>" }
```

If you save the previous script in a file like `csv2vrt.awk`, you can run it on a CVS file with a command like the following.

```sh
awk -f csv2vrt.awk black-body-table-byte-0256.csv
```

Hope that helps.

**Comment by roblabs** [comment]
The awk script is elegant and does the trick.  Much simpler than dealing with an XML parser.   

Thank you!

I did find that [GDAL](http://www.gdal.org/classGDALColorTable.html) has support for `GetColorEntry()` and `SetColorEntry()`, which after parsing the color table in Python you can easily get/set.


Here is an example of Kindlmann applied to a GeoTiff.

Thanks for fielding an "issue" on your web site!!

![kindlmann](https://cloud.githubusercontent.com/assets/118112/19045294/e4ca4d68-894c-11e6-962d-6008f397dacc.png)
