### ISSUE TITLE
problem with color palettes "inferno" and "smooth-cool-warm" based on RGB floating numbers

### ISSUE THREAD

**Issue by nbehrnd** [kennethmoreland-com/kennethmoreland-com.github.io#2]
Hello Kenneth,

with the aim to access each of the color palettes presented here under «color-advices» within gnuplot, I found the majority of those defined with RGBs as floating numbers well prepared to work with (e.g., [here](https://github.com/nbehrnd/moreland-gnuplot-palettes))

There are, however, two types currently not accessible for gnuplot: [inferno](https://github.com/kennethmoreland-com/kennethmoreland-com.github.io/tree/master/color-advice/inferno) and [smooth-cool-warm](https://github.com/kennethmoreland-com/kennethmoreland-com.github.io/tree/master/color-advice/smooth-cool-warm).  After rounding (most of) the entries in them to five decimals I found there are some RGB's exceeding the permitted range [0,1].  An addtional inspection showed that «my problematic entries» (after my conversion) with RGB beyond [0,1] inherited this property from the .csv shared by you.

_Assuming_ there could be a cosmetic curation of the symptons, rounding to less than five decimals like three or two was tested for the two problematic palette types alongside with two palette types known to pass well (viridis and bent-cool-warm, [temporary link](https://github.com/nbehrnd/palette_problem)).   While interesting _as such_ (e.g., your viridis palette is much more robust to such a constraint, than I thought), and yielding RGB tuples _formally_ within the range of RGB [0,1], retaining a lesser number of decimals equates to accessing only a fraction of the quality the palette definition originally provides.  This then is seen both while applying the palette on data, as well as requesting gnuplot to trace the channel's contributions (the «step shaped RGB traces» in gnuplot's `test sample` routine mentioned below).

_Maybe_ the issue wasn't considered here as you use RGB intergers [0,255] instead and wasn't seen despite they are around for months and years.  Because the other palettes work so well within current gnuplot 5.2.7b I _speculate_ the  transformation of RGB integers [0,255] to RGB floats [0,1] could contribute to the problem here.

Norwid

The data forked from your repository currently exhibiting problems and their md5sums are:
- in their last edit by Oct 3, 2018:
`a8012a38e7bbcc6dcdbc72bd2fe74dcb  inferno-table-float-0008.csv
1bbdc3dc18215f5bd67fd5656e10e380  inferno-table-float-0016.csv
3dae744147fa72ec0b84ed9c3886ed04  inferno-table-float-0032.csv
ca9ff19dc57f848cc4da058c27174c8b  inferno-table-float-0064.csv
7f1b7ed859dc8b6fc1fbeeea39ad04ca  inferno-table-float-0128.csv
f4e4aa9079ebd4de1f1d22bc4f249f25  inferno-table-float-0256.csv
be6cbf0119d1f9b48a4fd47987739b9b  inferno-table-float-0512.csv
c06adf56ba11d2239a8b7e80868579ed  inferno-table-float-1024.csv`

- in their last edit by Jan 10, 2016:
`03e888a6fa512aa7b15bf052c52ee491  smooth-cool-warm-table-float-0008.csv
a48dc453f56f616b5156314ac82ce87f  smooth-cool-warm-table-float-0016.csv
8fb2a755aa4a3273fa3a85a22350716d  smooth-cool-warm-table-float-0032.csv
23837866d3156f3d09fd2b7301cf3a1d  smooth-cool-warm-table-float-0064.csv
f5ae0894123e5967b6cc56da81dcaac0  smooth-cool-warm-table-float-0128.csv
3370b74bee1f7aebc6cb7b47ad0332b9  smooth-cool-warm-table-float-0256.csv
86c3890362a7348ee8900a0cb904ae8d  smooth-cool-warm-table-float-0512.csv
898dad5be0e90066d4e924776dfd79e1  smooth-cool-warm-table-float-1024.csv`

**Comment by nbehrnd** [comment]
In addition, the traces for R, G, B about RGB and Y/luminosit in the NTSC model gnuplot
draws as about _how_ the information is used to dye the levels become «step-shaped»
when passing from rounding the RGB floats from 5_decimals (e.g., [here](https://github.com/nbehrnd/palette_problem/blob/master/5_decimals/viridis_5_decimals/viridis_5_decimals.gif))
to 3_decimals (e.g., [here](https://github.com/nbehrnd/palette_problem/blob/master/3_decimals/viridis_3_decimals/viridis_3_decimals.gif) to eventual only one (e.g., [here](https://github.com/nbehrnd/palette_problem/blob/master/1_decimal/viridis_1_decimal/viridis_1_decimal.gif)).

_This_ kind of comparison of course is only possible for palettes «well accepted» in their
current form by gnuplot (e.g., bent-cool-warm, viridis); not so with «inferno» and «smooth-
cool-warm».  Interestingly, there was the palette with 16 explicitly defined colors of «smooth-
cool-warm» _was_ acceptable to gnuplot, which then yields in the concatention of the
animated .gif ([here](https://github.com/nbehrnd/palette_problem/blob/master/3_decimals/smooth-cool-warm_3_decimals/smooth-cool-warm_3_decimals.gif)) the brief «blink» about how the
map used in gnuplot could look like.

Hence, I suggest the see the .gif in each folder and the python scripts used to transform
your data (sub-folder tools), rather than downloading my whole project.

**Comment by kmorel** [comment]
@nbehrnd Thanks for alerting me to the errors in the inferno and smooth-cool-to-warm tables. I've made some edits to clamp everything to valid colors. I have not tried it in gnuplot, but based on your descriptions I expect the new tables to work.

**Comment by nbehrnd** [comment]
On Mon, 09 Dec 2019 10:19:32 -0800
Kenneth Moreland <notifications@github.com> wrote:

> @nbehrnd Thanks for alerting me to the errors in the inferno and
> smooth-cool-to-warm tables. I've made some edits to clamp everything
> to valid colors. I have not tried it in gnuplot, but based on your
> descriptions I expect the new tables to work.
> 

@kmorel  I'm able to confirm all in total 16 RGB-floating number
definitions for palette type «inferno» as well as «smooth-cool-warm»
now are accepted by gnuplot.  And they work well.  Thank you.
